using BepInEx.Configuration;
using UnityEngine;

namespace Nocturne;

internal static class NocturneConfig
{
    internal static ConfigEntry<KeyCode> MenuKey;
    internal static ConfigEntry<KeyCode> CopyCodeKey;
    internal static ConfigEntry<KeyCode> EndMatchKey;
    internal static ConfigEntry<KeyCode> CloseVotingKey;
    internal static ConfigEntry<KeyCode> CloseMeetingKey;
    internal static ConfigEntry<KeyCode> GodModeKey;
    internal static ConfigEntry<KeyCode> MirageKey;
    internal static ConfigEntry<KeyCode> VotekickKey;
    internal static ConfigEntry<KeyCode> VotekickAllKey;
    internal static ConfigEntry<KeyCode> VotekickHostKey;
    internal static ConfigEntry<KeyCode> RejoinLastKey;
    internal static ConfigEntry<KeyCode> VentKickSelectKey;
    internal static ConfigEntry<KeyCode> VentKickKey;
    internal static ConfigEntry<KeyCode> SabotageKey;
    internal static ConfigEntry<KeyCode> DoorsKey;
    internal static ConfigEntry<KeyCode> RadialKey;
    internal static ConfigEntry<KeyCode> InvisibleKey;
    internal static ConfigEntry<KeyCode> NoClipKey;
    internal static ConfigEntry<KeyCode> ZoomKey;
    internal static ConfigEntry<KeyCode> EventConsoleKey;
    internal static ConfigEntry<KeyCode> GhostKey;
    internal static ConfigEntry<KeyCode> GhostNowKey;
    internal static ConfigEntry<KeyCode> VentTpKey;
    internal static ConfigEntry<KeyCode> VentCycleKey;
    internal static ConfigEntry<KeyCode> SeeGhostsKey;
    internal static ConfigEntry<KeyCode> SpawnLobbyKey;
    internal static ConfigEntry<KeyCode> DespawnLobbyKey;
    internal static ConfigEntry<KeyCode> LeaveLobbyKey;
    internal static ConfigEntry<KeyCode> FunEggKey;
    internal static ConfigEntry<KeyCode> FunMorphKey;
    internal static ConfigEntry<KeyCode> FunRainbowKey;
    internal static ConfigEntry<KeyCode> FunSkinCycleKey;
    internal static ConfigEntry<KeyCode> FunBeatKey;
    internal static ConfigEntry<KeyCode> FunSizeKey;
    internal static ConfigEntry<KeyCode> FunMotionKey;
    internal static ConfigEntry<KeyCode> FunAnimKey;
    internal static ConfigEntry<KeyCode> FunResetKey;
    internal static ConfigEntry<KeyCode> ChatWindowKey;
    internal static ConfigEntry<KeyCode> OpenChatKey;
    internal static ConfigEntry<KeyCode> ChatSpamKey;
    internal static ConfigEntry<string> RadialFavorites;
    internal static ConfigEntry<bool> FpsLock30;
    internal static ConfigEntry<int> FpsCap;

    internal static ConfigEntry<bool> ShowFps;
    internal static ConfigEntry<bool> ShowHostLine;
    internal static ConfigEntry<bool> ShowLobbyTimer;
    internal static ConfigEntry<bool> Toasts;
    internal static ConfigEntry<bool> MenuButton;
    internal static ConfigEntry<float> MenuButtonX;
    internal static ConfigEntry<float> MenuButtonY;
    internal static ConfigEntry<bool> LobbyBrand;
    internal static ConfigEntry<bool> LobbyBar;

    internal static ConfigEntry<float> HudScale;
    internal static ConfigEntry<float> MenuScale;

    internal static ConfigEntry<bool> FreeCosmetics;
    internal static ConfigEntry<bool> ClassicBody;
    internal static ConfigEntry<bool> HideCosmeticsInMatch;
    internal static ConfigEntry<bool> AllowDuplicateColors;
    internal static ConfigEntry<bool> RandomOutfitSave;
    internal static ConfigEntry<bool> SnipeColor;
    internal static ConfigEntry<int> SnipeColorId;
    internal static ConfigEntry<bool> ColorAll;
    internal static ConfigEntry<int> ColorAllId;
    internal static ConfigEntry<string>[] FavoriteOutfits;

    internal static ConfigEntry<bool> RemoveGuestLimits;
    internal static ConfigEntry<bool> RemoveMinorLimits;
    internal static ConfigEntry<bool> ClearDisconnectPenalty;

    internal static ConfigEntry<bool> BlockTelemetry;

    internal static ConfigEntry<bool> AlwaysUnlockStartButton;
    internal static ConfigEntry<bool> QuickStartOnEnter;
    internal static ConfigEntry<bool> InstantStartOnEnter;
    internal static ConfigEntry<bool> AutoReturnLobbyAfterMatch;
    internal static ConfigEntry<bool> UnlockMatchKickBan;
    internal static ConfigEntry<bool> RichLobbyRows;
    internal static ConfigEntry<string> LobbySearchHost;
    internal static ConfigEntry<bool> JoinDetect;
    internal static ConfigEntry<bool> ModHandshake;

    internal static ConfigEntry<bool> AccessBanEnabled;
    internal static ConfigEntry<bool> AccessWhitelistOnly;
    internal static ConfigEntry<string> BanList;
    internal static ConfigEntry<string> WhiteList;
    internal static ConfigEntry<bool> MinLevelEnabled;
    internal static ConfigEntry<int> MinLevel;
    internal static ConfigEntry<string> MinLevelAction;
    internal static ConfigEntry<bool> MaxLevelEnabled;
    internal static ConfigEntry<int> MaxLevel;
    internal static ConfigEntry<string> MaxLevelAction;
    internal static ConfigEntry<bool> VoteKickProtect;
    internal static ConfigEntry<string> VoteKickAction;
    internal static ConfigEntry<bool> RpcGuard;
    internal static ConfigEntry<bool> ForceDtls;
    internal static ConfigEntry<bool> VentTpAuto;
    internal static ConfigEntry<float> VentTpAutoDelay;
    internal static ConfigEntry<string> RpcGuardAction;
    internal static ConfigEntry<bool> AntiBanHost;
    internal static ConfigEntry<string> AntiBanHostAction;
    internal static ConfigEntry<bool> KickFortegreen;
    internal static ConfigEntry<bool> BlockFakeMeetings;
    internal static ConfigEntry<bool> AccessNickBanEnabled;
    internal static ConfigEntry<string> NickBanList;
    internal static ConfigEntry<bool> AccessPlatformBanEnabled;
    internal static ConfigEntry<string> PlatformBanList;
    internal static ConfigEntry<bool> NameHistory;
    internal static ConfigEntry<bool> NotifyKnownPlayer;
    internal static ConfigEntry<bool> ShowBotJoins;
    internal static ConfigEntry<bool> ColorReservationsEnabled;

    internal static ConfigEntry<bool> VisualFreeCamera;
    internal static ConfigEntry<int> VisualFreeCameraSpeed;
    internal static ConfigEntry<bool> VisualCameraZoom;
    internal static ConfigEntry<bool> ZoomDuringTasks;
    internal static ConfigEntry<bool> VisualNoClip;
    internal static ConfigEntry<bool> HideModStamp;
    internal static ConfigEntry<bool> SkipShhh;
    internal static ConfigEntry<bool> MoonWalk;
    internal static ConfigEntry<bool> PlatformUnlock;
    internal static ConfigEntry<bool> NukeGame;
    internal static ConfigEntry<bool> HnsDrain;
    internal static ConfigEntry<float> HnsDrainStep;
    internal static ConfigEntry<bool> PhantomNoVanish;
    internal static ConfigEntry<bool> VentTpProtect;
    internal static ConfigEntry<bool> ZiplineProtect;
    internal static ConfigEntry<KeyCode> ZiplineSelectKey;
    internal static ConfigEntry<KeyCode> ZiplineDownKey;
    internal static ConfigEntry<KeyCode> ZiplineUpKey;
    internal static ConfigEntry<KeyCode> MeetingRoamKey;
    internal static ConfigEntry<bool> ChatCmdXmas;
    internal static ConfigEntry<bool> RevealRoles;
    internal static ConfigEntry<bool> VisualPlayerInfoNames;
    internal static ConfigEntry<bool> ShowPlayerIds;
    internal static ConfigEntry<bool> ShowPlayerFc;
    internal static ConfigEntry<bool> ShowVotekickCount;
    internal static ConfigEntry<bool> ForceNamesInHns;
    internal static ConfigEntry<bool> UnmaskShapeshifter;
    internal static ConfigEntry<bool> VisualAlwaysShowChat;
    internal static ConfigEntry<bool> OverheadChat;
    internal static ConfigEntry<int> OverheadChatTime;
    internal static ConfigEntry<int> OverheadChatWhere;
    internal static ConfigEntry<bool> Tracers;
    internal static ConfigEntry<bool> TracerBodies;
    internal static ConfigEntry<bool> KillTimers;
    internal static ConfigEntry<bool> Radar;
    internal static ConfigEntry<bool> RadarBodies;
    internal static ConfigEntry<bool> RadarTeleport;
    internal static ConfigEntry<bool> RadarDoors;
    internal static ConfigEntry<bool> RadarLocked;
    internal static ConfigEntry<float> RadarX;
    internal static ConfigEntry<float> RadarY;
    internal static ConfigEntry<int> RadarSize;
    internal static ConfigEntry<int> RadarOpacity;
    internal static ConfigEntry<bool> EspBoxes;
    internal static ConfigEntry<bool> EspNames;
    internal static ConfigEntry<bool> EspDead;
    internal static ConfigEntry<bool> EspSeeImps;
    internal static ConfigEntry<bool> EspSeeAngels;
    internal static ConfigEntry<bool> EspSeeCrew;
    internal static ConfigEntry<bool> EspSideColors;
    internal static ConfigEntry<int> EspCrewColor;
    internal static ConfigEntry<int> EspImpColor;
    internal static ConfigEntry<int> EspDeadColor;
    internal static ConfigEntry<bool> SeeVents;
    internal static ConfigEntry<bool> SeeGhosts;
    internal static ConfigEntry<bool> SeePhantoms;
    internal static ConfigEntry<bool> SeeProtections;
    internal static ConfigEntry<bool> TaskArrows;
    internal static ConfigEntry<bool> Wallhack;
    internal static ConfigEntry<bool> NeonOutline;
    internal static ConfigEntry<int> NeonOutlineMode;
    internal static ConfigEntry<bool> CommsBypass;
    internal static ConfigEntry<bool> RevealVotes;
    internal static ConfigEntry<bool> RevealAnonVotes;
    internal static ConfigEntry<bool> VkCopyCode;
    internal static ConfigEntry<bool> VkRejoin;
    internal static ConfigEntry<bool> VkAutoRejoin;
    internal static ConfigEntry<bool> GodMode;
    internal static ConfigEntry<bool> LagComp;
    internal static ConfigEntry<bool> LagCompFreeze;
    internal static ConfigEntry<bool> LagCompJitter;
    internal static ConfigEntry<int> LagCompJitterMin;
    internal static ConfigEntry<int> LagCompJitterMax;
    internal static ConfigEntry<bool> SpeedMod;
    internal static ConfigEntry<float> SpeedMult;
    internal static ConfigEntry<bool> InvertControls;
    internal static ConfigEntry<bool> Invisible;
    internal static ConfigEntry<bool> FakeScan;
    internal static ConfigEntry<bool> AutoTasks;
    internal static ConfigEntry<float> AutoTasksDelay;
    internal static ConfigEntry<bool> SabAutoFix;
    internal static ConfigEntry<bool> ConsoleReach;
    internal static ConfigEntry<float> ConsoleDist;
    internal static ConfigEntry<bool> SkipDecon;
    internal static ConfigEntry<bool> AirshipSpawn;
    internal static ConfigEntry<int> AirshipSpawnId;
    internal static ConfigEntry<bool> FakeCams;
    internal static ConfigEntry<bool> BuffNoCd;
    internal static ConfigEntry<bool> BuffVentAny;
    internal static ConfigEntry<bool> BuffVentWalk;
    internal static ConfigEntry<bool> VentNetwork;
    internal static ConfigEntry<bool> BuffKillReach;
    internal static ConfigEntry<float> BuffKillDist;
    internal static ConfigEntry<bool> BuffKillAny;
    internal static ConfigEntry<bool> BuffKillAura;
    internal static ConfigEntry<bool> AutoVentKill;
    internal static ConfigEntry<bool> BodyToVent;
    internal static ConfigEntry<bool> BuffNoKillCd;
    internal static ConfigEntry<bool> BuffVanishKill;
    internal static ConfigEntry<bool> BuffPhVanish;
    internal static ConfigEntry<bool> BuffVentSab;
    internal static ConfigEntry<bool> BuffSsForever;
    internal static ConfigEntry<bool> BuffSsQuiet;
    internal static ConfigEntry<bool> BuffAutoReport;
    internal static ConfigEntry<bool> BuffEngVent;
    internal static ConfigEntry<bool> BuffEngCd;
    internal static ConfigEntry<bool> BuffSciBat;
    internal static ConfigEntry<bool> BuffSciCd;
    internal static ConfigEntry<bool> BuffDetReach;
    internal static ConfigEntry<bool> BuffImpTasks;
    internal static ConfigEntry<bool> BuffMapCd;
    internal static ConfigEntry<float> ChatSpamDelay;
    internal static ConfigEntry<bool> DoorKeepOpen;
    internal static ConfigEntry<bool> SabAutoLights;
    internal static ConfigEntry<bool> SabSpamReactor;
    internal static ConfigEntry<bool> SabInfMushroom;
    internal static ConfigEntry<bool> MultiSabotage;
    internal static ConfigEntry<bool> VoteImmune;
    internal static ConfigEntry<bool> NoReports;
    internal static ConfigEntry<bool> MouseTeleport;
    internal static ConfigEntry<bool> MouseSelect;
    internal static ConfigEntry<bool> SelfDrag;
    internal static ConfigEntry<bool> SelfDragSmooth;
    internal static ConfigEntry<float> SelfDragSpeed;
    internal static ConfigEntry<bool> GhostAfterStart;
    internal static ConfigEntry<bool> GameMaster;
    internal static ConfigEntry<int> FakeMapId;

    internal static ConfigEntry<bool> NameColor;
    internal static ConfigEntry<int> NameColorStyle;
    internal static ConfigEntry<bool> NameColorAnimated;
    internal static ConfigEntry<bool> ChatLog;
    internal static ConfigEntry<bool> ColorCmd;
    internal static ConfigEntry<bool> ColorCmdNotify;
    internal static ConfigEntry<bool> ChatCmds;
    internal static ConfigEntry<bool> BanWords;

    internal static ConfigEntry<string> LobbyPresets;

    internal static ConfigEntry<bool> LobbyCloneMode;
    internal static ConfigEntry<bool> LobbyCloneShadow;
    internal static ConfigEntry<bool> LobbyCloneGuard;
    internal static ConfigEntry<float> LobbyCloneGuardRadius;
    internal static ConfigEntry<bool> LobbyCloneDrift;
    internal static ConfigEntry<int> LobbyCloneMax;
    internal static ConfigEntry<int> LobbyCloneSpawnCount;
    internal static ConfigEntry<int> NetCloneCount;
    internal static ConfigEntry<bool> NetCloneMode;
    internal static ConfigEntry<int> LobbyCloneColorId;
    internal static ConfigEntry<float> LobbyCloneScale;
    internal static ConfigEntry<int> CloneFormation;
    internal static ConfigEntry<float> CloneFormationScale;
    internal static ConfigEntry<bool> CloneFormationAnim;
    internal static ConfigEntry<bool> CloneNaked;
    internal static ConfigEntry<float> CloneFormationAnimSpeed;
    internal static ConfigEntry<int> LobbyCloneFormationCopies;

    internal static ConfigEntry<bool> BetterChat;
    internal static ConfigEntry<bool> ChatWindow;
    internal static ConfigEntry<int> ChatHistorySize;
    internal static ConfigEntry<bool> DarkChatTheme;
    internal static ConfigEntry<bool> ChatBubbleSenderInfo;
    internal static ConfigEntry<bool> ChatTimestamps;
    internal static ConfigEntry<bool> UnlimitedChatLength;
    internal static ConfigEntry<bool> SkipChatCooldown;
    internal static ConfigEntry<bool> GhostChat;

    internal static ConfigEntry<bool> AutoHostEnabled;
    internal static ConfigEntry<int> AutoHostMinPlayers;
    internal static ConfigEntry<int> AutoHostStartDelaySeconds;
    internal static ConfigEntry<int> AutoHostBackoffSeconds;
    internal static ConfigEntry<bool> AutoHostInstantStart;
    internal static ConfigEntry<int> AutoHostWarmupSeconds;
    internal static ConfigEntry<int> AutoHostLoadGraceSeconds;
    internal static ConfigEntry<int> AutoHostFastStartPlayers;
    internal static ConfigEntry<int> AutoHostFastStartDelaySeconds;
    internal static ConfigEntry<int> AutoHostForceAfterMinutes;
    internal static ConfigEntry<int> AutoHostForceMinPlayers;
    internal static ConfigEntry<bool> AutoHostCancelBelowMin;
    internal static ConfigEntry<bool> AutoHostWaitLoadedPlayers;
    internal static ConfigEntry<bool> AutoHostReturnAfterMatch;
    internal static ConfigEntry<bool> AutoHostForceLastMinute;

    internal static ConfigEntry<bool> DummyEnabled;
    internal static ConfigEntry<KeyCode> DummyKey;
    internal static ConfigEntry<bool> DummyDoTasks;
    internal static ConfigEntry<bool> DummyFixSabotage;
    internal static ConfigEntry<bool> DummyReportBodies;
    internal static ConfigEntry<bool> AutoHostNotifications;

    internal static ConfigEntry<string> MusicAccent;
    internal static ConfigEntry<int> MusicEqPreset;
    internal static ConfigEntry<KeyCode> MusicPrevKey;
    internal static ConfigEntry<KeyCode> MusicNextKey;
    internal static ConfigEntry<KeyCode> MusicPlayPauseKey;
    internal static ConfigEntry<KeyCode> MusicStopKey;
    internal static ConfigEntry<KeyCode> MusicVolumeUpKey;
    internal static ConfigEntry<KeyCode> MusicVolumeDownKey;
    internal static ConfigEntry<KeyCode> MusicToggleKey;

    internal static ConfigEntry<bool> BugRoomCycle;
    internal static ConfigEntry<bool> BugRoomHunt;
    internal static ConfigEntry<string> BugRoomTargets;
    internal static ConfigEntry<bool> BugRoomLog;
    internal static ConfigEntry<float> BugRoomDelay;

    internal static ConfigEntry<bool> LobbySnow;
    internal static ConfigEntry<int> LobbyWeather;
    internal static ConfigEntry<int> LobbySnowAmount;
    internal static ConfigEntry<bool> LobbyTheme;
    internal static ConfigEntry<bool> MainMenuArt;
    internal static ConfigEntry<bool> LobbyAnims;

    internal static ConfigEntry<bool> NoWinConditions;
    internal static ConfigEntry<bool> HideAndSeekTwoSeekers;
    internal static ConfigEntry<int> SeekerCount;
    internal static ConfigEntry<bool> SeekerInstantStart;
    internal static ConfigEntry<bool> FourImpostors;
    internal static ConfigEntry<bool> LooseHostOptions;
    internal static ConfigEntry<bool> ForceMinValues;
    internal static ConfigEntry<bool> CopyCodeOnDisconnect;

    internal static ConfigEntry<string> Language;
    internal static ConfigEntry<int> ThemeIndex;

    internal static ConfigEntry<string> BodyMode;
    internal static ConfigEntry<bool> MuteLobbyMusic;
    internal static ConfigEntry<bool> SpoofPlatformEnabled;
    internal static ConfigEntry<int> SpoofPlatformIndex;
    internal static ConfigEntry<bool> SpoofLevelEnabled;
    internal static ConfigEntry<int> SpoofLevelValue;
    internal static ConfigEntry<bool> SpoofDeviceId;
    internal static ConfigEntry<bool> SpoofFriendCodeEnabled;
    internal static ConfigEntry<string> SpoofFriendCodeValue;

    internal static ConfigEntry<bool> EventNotify;
    internal static ConfigEntry<bool> EventConsole;
    internal static ConfigEntry<bool> EventNotifyChat;
    internal static ConfigEntry<int> EventFilterMask;
    internal static ConfigEntry<bool> ReplayView;
    internal static ConfigEntry<int> ReplayFilterMask;
    internal static ConfigEntry<KeyCode> ReplayKey;
    internal static ConfigEntry<bool> ReplayClearAfterMeeting;
    internal static ConfigEntry<bool> NotifyVotekick;
    internal static ConfigEntry<bool> NotifySabotage;
    internal static ConfigEntry<bool> NotifyKill;
    internal static ConfigEntry<bool> SecurityNotify;
    internal static ConfigEntry<bool> NotifyMeeting;
    internal static ConfigEntry<bool> NotifyEject;

    internal static void Bind(ConfigFile config)
    {
        MenuKey = config.Bind("Keys", "MenuKey", KeyCode.Insert, "Open/close the menu.");
        CopyCodeKey = config.Bind("Keys", "CopyCodeKey", KeyCode.F6, "Copy the lobby code.");
        EndMatchKey = config.Bind("Keys", "EndMatchKey", KeyCode.End, "End the match (host).");
        CloseVotingKey = config.Bind("Keys", "CloseVotingKey", KeyCode.None, "Force-close voting, tally cast votes (host).");
        CloseMeetingKey = config.Bind("Keys", "CloseMeetingKey", KeyCode.None, "Force-close the meeting with no ejection (host).");
        GodModeKey = config.Bind("Keys", "GodModeKey", KeyCode.None, "Toggle God Mode.");
        MirageKey = config.Bind("Keys", "MirageKey", KeyCode.None, "Toggle Mirage (desync).");
        VotekickKey = config.Bind("Keys", "VotekickKey", KeyCode.None, "Toggle auto votekick.");
        VotekickAllKey = config.Bind("Keys", "VotekickAllKey", KeyCode.None, "Votekick everyone (lobby vote-ban).");
        VotekickHostKey = config.Bind("Keys", "VotekickHostKey", KeyCode.None, "Votekick the host (lobby vote-ban).");
        RejoinLastKey = config.Bind("Keys", "RejoinLastKey", KeyCode.None, "Rejoin the last game by saved code.");
        VentKickSelectKey = config.Bind("Keys", "VentKickSelectKey", KeyCode.None, "Select all players for vent kick.");
        VentKickKey = config.Bind("Keys", "VentKickKey", KeyCode.None, "Vent kick the selected players.");
        SabotageKey = config.Bind("Keys", "SabotageKey", KeyCode.None, "Sabotage all (host, in match).");
        DoorsKey = config.Bind("Keys", "DoorsKey", KeyCode.None, "Close all doors (host, in match).");
        RadialKey = config.Bind("Keys", "RadialKey", KeyCode.None, "Hold to open the radial quick menu.");
        InvisibleKey = config.Bind("Keys", "InvisibleKey", KeyCode.None, "Toggle invisibility.");
        NoClipKey = config.Bind("Keys", "NoClipKey", KeyCode.None, "Toggle no-clip.");
        ZoomKey = config.Bind("Keys", "ZoomKey", KeyCode.None, "Toggle wheel zoom.");
        EventConsoleKey = config.Bind("Keys", "EventConsoleKey", KeyCode.None, "Toggle the event console window.");
        GhostKey = config.Bind("Keys", "GhostKey", KeyCode.None, "Toggle ghost after start.");
        GhostNowKey = config.Bind("Keys", "GhostNowKey", KeyCode.None, "Suicide in match (impostor only).");
        VentTpKey = config.Bind("Keys", "VentTpKey", KeyCode.None, "Teleport marked players to the selected vent.");
        VentCycleKey = config.Bind("Keys", "VentCycleKey", KeyCode.None, "Cycle the target vent for teleport.");
        SeeGhostsKey = config.Bind("Keys", "SeeGhostsKey", KeyCode.None, "Toggle see ghosts.");
        SpawnLobbyKey = config.Bind("Keys", "SpawnLobbyKey", KeyCode.None, "Spawn/recreate the lobby (host).");
        DespawnLobbyKey = config.Bind("Keys", "DespawnLobbyKey", KeyCode.None, "Despawn/destroy the lobby (host).");
        LeaveLobbyKey = config.Bind("Keys", "LeaveLobbyKey", KeyCode.None, "Leave the lobby/match (press twice to confirm).");
        FunEggKey = config.Bind("Keys", "FunEggKey", KeyCode.None, "Fun: all to eggs (host).");
        FunMorphKey = config.Bind("Keys", "FunMorphKey", KeyCode.None, "Fun: morph all into selected (host).");
        FunRainbowKey = config.Bind("Keys", "FunRainbowKey", KeyCode.None, "Fun: toggle rainbow (host).");
        FunSkinCycleKey = config.Bind("Keys", "FunSkinCycleKey", KeyCode.None, "Fun: toggle cosmetic cycle (host).");
        FunBeatKey = config.Bind("Keys", "FunBeatKey", KeyCode.None, "Fun: cycle beat sync (host).");
        FunSizeKey = config.Bind("Keys", "FunSizeKey", KeyCode.None, "Fun: cycle size (host).");
        FunMotionKey = config.Bind("Keys", "FunMotionKey", KeyCode.None, "Fun: cycle motion (host).");
        FunAnimKey = config.Bind("Keys", "FunAnimKey", KeyCode.None, "Fun: cycle animation (host).");
        FunResetKey = config.Bind("Keys", "FunResetKey", KeyCode.None, "Fun: reset appearance (host).");
        ChatWindowKey = config.Bind("Keys", "ChatWindowKey", KeyCode.None, "Toggle the draggable chat window.");
        OpenChatKey = config.Bind("Keys", "OpenChatKey", KeyCode.None, "Open/close the vanilla game chat.");
        ChatSpamKey = config.Bind("Keys", "ChatSpamKey", KeyCode.None, "Toggle chat auto-spam (Chat Sender).");
        MeetingRoamKey = config.Bind("Keys", "MeetingRoamKey", KeyCode.None, "Close the meeting locally and roam.");
        RadialFavorites = config.Bind("Interface", "RadialFavorites", "", "Radial favorites (feature ids, comma-separated).");
        FpsLock30 = config.Bind("QoL", "FpsLock30", false, "Lock FPS to 30.");
        FpsCap = config.Bind("QoL", "FpsCap", 60, "FPS cap when not locked to 30 (300 = unlimited).");
        FpsCap.Value = Mathf.Clamp(FpsCap.Value, 30, 300);

        ShowFps = config.Bind("QoL", "ShowFps", true, "FPS counter.");
        ShowHostLine = config.Bind("QoL", "ShowHostLine", true, "Show who hosts the room under the FPS line.");
        ShowLobbyTimer = config.Bind("QoL", "ShowLobbyTimer", true, "Lobby lifetime timer.");
        Toasts = config.Bind("QoL", "Toasts", true, "Pop-up notifications.");
        MenuButton = config.Bind("QoL", "MenuButton", false, "On-screen button under the Nocturne badge to open the menu (touch-friendly).");
        MenuButtonX = config.Bind("QoL", "MenuButtonX", -1f, "Saved X of the on-screen menu button (-1 = auto).");
        MenuButtonY = config.Bind("QoL", "MenuButtonY", -1f, "Saved Y of the on-screen menu button (-1 = auto).");
        LobbyBrand = config.Bind("Lobby", "Brand", true, "Nocturne watermark in the lobby.");
        LobbyBar = config.Bind("Lobby", "LobbyBar", true, "Custom lobby bar (host avatar, START button, FPS/ping/time chips).");

        HudScale = config.Bind("QoL", "HudScale", 1f, "HUD scale.");
        MenuScale = config.Bind("QoL", "MenuScale", 1f, "Menu scale multiplier.");

        FreeCosmetics = config.Bind("Cosmetics", "UnlockCosmetics", true, "Mark cosmetics and bundles as owned on this client.");
        ClassicBody = config.Bind("Cosmetics", "ClassicBody", false, "Client-side: render players with the classic (nostalgia) body.");
        HideCosmeticsInMatch = config.Bind("Cosmetics", "HideCosmeticsInMatch", false, "Hide cosmetics on this client during a match.");
        AllowDuplicateColors = config.Bind("Cosmetics", "AllowDuplicateColors", false, "Host: let several players share one color.");
        RandomOutfitSave = config.Bind("Cosmetics", "RandomOutfitSave", false, "Random outfit also overwrites and saves your profile.");
        SnipeColor = config.Bind("Cosmetics", "SnipeColor", false, "Grab the wanted color as soon as it frees up.");
        SnipeColorId = config.Bind("Cosmetics", "SnipeColorId", 0, "Color to snipe (0-17).");
        ColorAll = config.Bind("Cosmetics", "ColorAll", false, "Host: force all players to one color (also new joiners).");
        ColorAllId = config.Bind("Cosmetics", "ColorAllId", 6, "Color for Color All (0-17, 6 = black).");
        FavoriteOutfits = new ConfigEntry<string>[4];
        for (int i = 0; i < FavoriteOutfits.Length; i++)
            FavoriteOutfits[i] = config.Bind("Cosmetics", $"FavoriteOutfit{i + 1}", "", $"Saved outfit, slot {i + 1}.");


        RemoveGuestLimits = config.Bind("Account", "RemoveGuestLimits", false, "Give guests extra client-side account features.");
        RemoveMinorLimits = config.Bind("Account", "RemoveMinorLimits", false, "Bypass client-side age limits and waiting.");
        ClearDisconnectPenalty = config.Bind("Account", "ClearDisconnectPenalty", true, "Keep the local disconnect penalty from growing.");

        BlockTelemetry = config.Bind("Privacy", "BlockTelemetry", true, "Disable analytics, crash reports and performance reporting.");

        AlwaysUnlockStartButton = config.Bind("Lobby", "AlwaysUnlockStartButton", true, "Keep the Start button active for the host (MinPlayers=1).");
        QuickStartOnEnter = config.Bind("Lobby", "QuickStartOnEnter", true, "Enter in the lobby triggers Start when chat is not focused.");
        InstantStartOnEnter = config.Bind("Lobby", "InstantStartOnEnter", true, "Skip the countdown when starting with Enter.");
        AutoReturnLobbyAfterMatch = config.Bind("Lobby", "AutoReturnLobbyAfterMatch", true, "Auto-return to the lobby from post-match screens.");
        UnlockMatchKickBan = config.Bind("Advanced", "UnlockMatchKickBan", true, "Host: kick/ban buttons available during a match.");
        RichLobbyRows = config.Bind("Lobby", "RichLobbyRows", true, "Rich lobby browser: up to 24 rows, host/code/platform/age.");
        LobbySearchHost = config.Bind("Lobby", "LobbySearchHost", "", "Show only lobbies whose host name contains this text (empty = all).");
        JoinDetect = config.Bind("Players", "JoinDetect", true, "Join detect: platform, level and raw platform name.");
        ModHandshake = config.Bind("Players", "ModHandshake", true, "Toast when another Nocturne user is in the lobby.");

        AccessBanEnabled = config.Bind("Guard", "AccessBanEnabled", true, "Kick/ban players from the ban list on join.");
        AccessWhitelistOnly = config.Bind("Guard", "AccessWhitelistOnly", false, "Kick everyone not in the whitelist.");
        BanList = config.Bind("Guard", "BanList", "", "Ban list (FriendCode, comma-separated).");
        WhiteList = config.Bind("Guard", "WhiteList", "", "Whitelist (FriendCode, comma-separated).");
        MinLevelEnabled = config.Bind("Guard", "MinLevelEnabled", false, "React to players below the minimum level.");
        MinLevel = config.Bind("Guard", "MinLevel", 1, "Minimum level.");
        MinLevel.Value = Mathf.Clamp(MinLevel.Value, 1, 500);
        MinLevelAction = config.Bind("Guard", "MinLevelAction", "Kick", "Action on low level: Kick, Ban.");
        MaxLevelEnabled = config.Bind("Guard", "MaxLevelEnabled", false, "React to players above the maximum level.");
        MaxLevel = config.Bind("Guard", "MaxLevel", 500, "Maximum level.");
        MaxLevel.Value = Mathf.Clamp(MaxLevel.Value, 1, 999);
        MaxLevelAction = config.Bind("Guard", "MaxLevelAction", "Kick", "Action on high level: Kick, Ban.");
        VoteKickProtect = config.Bind("Guard", "VoteKickProtect", true, "Block vote-kicks in the lobby.");
        VoteKickAction = config.Bind("Guard", "VoteKickAction", "Kick", "Action on the voter: Null, Warn, Kick, Ban.");
        RpcGuard = config.Bind("Guard", "RpcGuard", false, "Detect impossible RPCs by role/map (sabotage as crew, illegal vent, etc.).");
        ForceDtls = config.Bind("Guard", "ForceDtls", true, "Force DTLS connection (bypasses server RPC anticheat that kicks off-host actions).");
        VentTpAuto = config.Bind("Cheats", "VentTpAuto", false, "Auto-scatter marked players across vents on an interval.");
        VentTpAutoDelay = config.Bind("Cheats", "VentTpAutoDelay", 1f, "Interval for auto vent scatter (0.3-10 s).");
        VentTpAutoDelay.Value = Mathf.Clamp(VentTpAutoDelay.Value, 0.3f, 10f);
        RpcGuardAction = config.Bind("Guard", "RpcGuardAction", "Kick", "Action on the cheater: Null, Warn, Kick, Ban.");
        AntiBanHost = config.Bind("Guard", "AntiBanHost", false, "As host, punish the sender of the ban/crash exploit.");
        AntiBanHostAction = config.Bind("Guard", "AntiBanHostAction", "Ban", "Action on the sender: Null, Warn, Kick, Ban.");
        KickFortegreen = config.Bind("Guard", "KickFortegreen", true, "Host: kick players with the Fortegreen color.");
        BlockFakeMeetings = config.Bind("Guard", "BlockFakeMeetings", false, "Block fake meeting UI in the lobby and drop spawn floods (anti-freeze).");
        AccessNickBanEnabled = config.Bind("Guard", "AccessNickBanEnabled", false, "Kick/ban players from the nick ban list by name.");
        NickBanList = config.Bind("Guard", "NickBanList", "", "Nick ban list (nicks separated by ;).");
        AccessPlatformBanEnabled = config.Bind("Guard", "AccessPlatformBanEnabled", false, "Kick/ban players whose raw platform name is on the list.");
        PlatformBanList = config.Bind("Guard", "PlatformBanList", "", "Platform ban list (raw platform names separated by ;).");
        NameHistory = config.Bind("Guard", "NameHistory", true, "Remember nicks by FriendCode and notify on changes.");
        NotifyKnownPlayer = config.Bind("Guard", "NotifyKnownPlayer", true, "Notify when a player you already met joins.");
        ShowBotJoins = config.Bind("Guard", "ShowBotJoins", false, "Show join toasts for bots (raw platform contains 'bot'). Off = hidden.");
        ColorReservationsEnabled = config.Bind("Guard", "ColorReservationsEnabled", false, "Host: auto-apply a reserved color to a player by FriendCode on join.");

        VisualFreeCamera = config.Bind("Visual", "FreeCamera", false, "Free WASD camera in the lobby.");
        VisualFreeCameraSpeed = config.Bind("Visual", "FreeCameraSpeed", 11, "Free camera speed.");
        VisualFreeCameraSpeed.Value = Mathf.Clamp(VisualFreeCameraSpeed.Value, 4, 30);
        VisualCameraZoom = config.Bind("Visual", "CameraZoom", false, "Camera zoom-out with the mouse wheel (everywhere), unlimited.");
        ZoomDuringTasks = config.Bind("Visual", "ZoomDuringTasks", false, "Keep the camera zoom while a task minigame is open.");
        VisualNoClip = config.Bind("Visual", "NoClip", false, "No-clip: disable the local player collider (lobby and match).");
        HideModStamp = config.Bind("Visual", "HideModStamp", false, "Client-side: hide the yellow MOD badge (stealth).");
        SkipShhh = config.Bind("Visual", "SkipShhh", false, "Skip the 'Shhh!' intro screen.");
        MoonWalk = config.Bind("Visual", "MoonWalk", false, "Moonwalk: glide in the idle pose instead of the walk animation.");
        PlatformUnlock = config.Bind("Cheats", "PlatformUnlock", false, "Airship: re-enable the moving platform in Hide and Seek.");
        NukeGame = config.Bind("Cheats", "NukeGame", false, "Spam-call meetings back to back.");
        HnsDrain = config.Bind("Cheats", "HnsDrain", false, "Hide and Seek: resend task completions to drain the crew timer.");
        HnsDrainStep = config.Bind("Cheats", "HnsDrainStep", 0.25f, "Seconds between drain bursts (0.15-1.5).");
        HnsDrainStep.Value = Mathf.Clamp(HnsDrainStep.Value, 0.15f, 1.5f);
        PhantomNoVanish = config.Bind("Cheats", "PhantomNoVanish", false, "Phantom: send the vanish smoke off-map so nobody sees where you vanished.");
        VentTpProtect = config.Bind("Guard", "VentTpProtect", false, "Block forced vent teleport/boot aimed at you.");
        ZiplineProtect = config.Bind("Guard", "ZiplineProtect", false, "Block forced zipline rides aimed at you.");
        ZiplineSelectKey = config.Bind("Keys", "ZiplineSelectKey", KeyCode.None, "Select every other player as a ride target.");
        ZiplineDownKey = config.Bind("Keys", "ZiplineDownKey", KeyCode.None, "Send selected down the zipline.");
        ZiplineUpKey = config.Bind("Keys", "ZiplineUpKey", KeyCode.None, "Send selected up the zipline.");
        ChatCmdXmas = config.Bind("Chat", "ChatCmdXmas", true, "Host: let players toggle rainbow colors with /xmas in chat.");
        RevealRoles = config.Bind("Visual", "RevealRoles", false, "Show each player's role above their name (by color).");
        VisualPlayerInfoNames = config.Bind("Visual", "PlayerInfoNames", false, "Level/platform/host above names in the lobby.");
        ShowPlayerIds = config.Bind("Visual", "ShowPlayerIds", false, "Show player id above names.");
        ShowPlayerFc = config.Bind("Visual", "ShowPlayerFc", false, "Show friend code above names.");
        ShowVotekickCount = config.Bind("Visual", "ShowVotekickCount", false, "Show how many votekicks a player has above their name.");
        ForceNamesInHns = config.Bind("Visual", "ForceNamesInHns", true, "Keep nicknames visible in Hide and Seek.");
        UnmaskShapeshifter = config.Bind("Visual", "UnmaskShapeshifter", false, "Show the real player under a shapeshifter disguise.");
        VisualAlwaysShowChat = config.Bind("Visual", "AlwaysShowChat", true, "Keep chat always visible.");
        OverheadChat = config.Bind("Visual", "OverheadChat", false, "Show chat messages above players like speech bubbles.");
        OverheadChatTime = config.Bind("Visual", "OverheadChatTime", 6, "How long an overhead message stays (2-15 s).");
        OverheadChatTime.Value = Mathf.Clamp(OverheadChatTime.Value, 2, 15);
        OverheadChatWhere = config.Bind("Visual", "OverheadChatWhere", 0, "Where overhead chat shows: 0 lobby and match, 1 match only, 2 lobby only.");
        OverheadChatWhere.Value = Mathf.Clamp(OverheadChatWhere.Value, 0, 2);
        Tracers = config.Bind("Visual", "Tracers", false, "Lines to other players in a match.");
        TracerBodies = config.Bind("Visual", "TracerBodies", false, "Tracers to bodies too (yellow).");
        KillTimers = config.Bind("Visual", "KillTimers", false, "Kill cooldown above killer players.");
        Radar = config.Bind("Visual", "Radar", false, "Minimap radar with player dots.");
        RadarBodies = config.Bind("Visual", "RadarBodies", true, "Show dead bodies on the radar.");
        RadarTeleport = config.Bind("Visual", "RadarTeleport", false, "Right-click the radar to teleport there.");
        RadarDoors = config.Bind("Visual", "RadarDoors", false, "Impostor: door-close buttons on the radar rooms.");
        RadarLocked = config.Bind("Visual", "RadarLocked", false, "Lock the radar position (can't be dragged).");
        RadarX = config.Bind("Visual", "RadarX", 12f, "Radar X position (drag to move).");
        RadarY = config.Bind("Visual", "RadarY", 60f, "Radar Y position (drag to move).");
        RadarSize = config.Bind("Visual", "RadarSize", 100, "Radar size, percent (60-180).");
        RadarOpacity = config.Bind("Visual", "RadarOpacity", 93, "Radar opacity, percent (30-100).");
        RadarSize.Value = Mathf.Clamp(RadarSize.Value, 60, 180);
        RadarOpacity.Value = Mathf.Clamp(RadarOpacity.Value, 30, 100);
        EspBoxes = config.Bind("Visual", "EspBoxes", false, "Boxes around players, seen through walls.");
        EspNames = config.Bind("Visual", "EspNames", true, "Name and distance over ESP boxes.");
        EspSeeImps = config.Bind("Visual", "EspSeeImps", true, "ESP: impostor side (impostor, shapeshifter, phantom, viper).");
        EspSeeAngels = config.Bind("Visual", "EspSeeAngels", true, "ESP: guardian angel.");
        EspSeeCrew = config.Bind("Visual", "EspSeeCrew", true, "ESP: crewmate side (all crew roles).");
        EspDead = config.Bind("Visual", "EspDead", false, "Show dead players on ESP too.");
        EspSideColors = config.Bind("Visual", "EspSideColors", false, "Color ESP/tracers by side (crew/impostor/dead) instead of body color.");
        EspCrewColor = config.Bind("Visual", "EspCrewColor", 0, "ESP color index for crewmates.");
        EspImpColor = config.Bind("Visual", "EspImpColor", 1, "ESP color index for impostors.");
        EspDeadColor = config.Bind("Visual", "EspDeadColor", 2, "ESP color index for dead bodies.");
        SeeVents = config.Bind("Visual", "SeeVents", false, "Reveal players hiding in vents.");
        SeeGhosts = config.Bind("Visual", "SeeGhosts", false, "See dead players (ghosts) while alive.");
        SeePhantoms = config.Bind("Visual", "SeePhantoms", false, "See a Phantom while they are invisible.");
        SeeProtections = config.Bind("Visual", "SeeProtections", false, "Always show the Guardian Angel shield on protected players.");
        TaskArrows = config.Bind("Visual", "TaskArrows", false, "On-screen arrows pointing to your unfinished tasks.");
        Wallhack = config.Bind("Visual", "Wallhack", false, "Remove the vision darkness — see the whole map and all players through walls.");
        NeonOutline = config.Bind("Visual", "NeonOutline", false, "Neon glow outline around players (client-side).");
        NeonOutlineMode = config.Bind("Visual", "NeonOutlineMode", 1, "Outline color: 0 rainbow, 1 by role (imp red / crew green), 2 player color.");
        NeonOutlineMode.Value = Mathf.Clamp(NeonOutlineMode.Value, 0, 2);
        CommsBypass = config.Bind("Visual", "CommsBypass", false, "Ignore comms sabotage locally: tasks and role abilities keep working.");
        RevealVotes = config.Bind("Visual", "RevealVotes", false, "Show meeting votes before the reveal.");
        RevealAnonVotes = config.Bind("Visual", "RevealAnonVotes", true, "Recolor vote icons to real voter, ignoring anonymous mode.");
        VkCopyCode = config.Bind("Player", "VkCopyCode", true, "Copy lobby code to clipboard during auto votekick.");
        VkRejoin = config.Bind("Player", "VkRejoin", false, "Auto rejoin the lobby by code between votekick rounds.");
        VkAutoRejoin = config.Bind("Player", "VkAutoRejoin", false, "Non-host: auto-rejoin when 2 players votekick you (resets the votes).");
        GodMode = config.Bind("Player", "GodMode", false, "Immortality via fake vent presence.");
        LagComp = config.Bind("Player", "LagComp", false, "Lag compensation: manipulate the position others see (you move normally).");
        LagCompFreeze = config.Bind("Player", "LagCompFreeze", false, "Freeze: appear stationary to others.");
        LagCompJitter = config.Bind("Player", "LagCompJitter", true, "Jitter: random desync intervals.");
        LagCompJitterMin = config.Bind("Player", "LagCompJitterMin", 2, "Jitter min frames held (1-30).");
        LagCompJitterMax = config.Bind("Player", "LagCompJitterMax", 4, "Jitter max frames held (1-30).");
        SpeedMod = config.Bind("Player", "SpeedMod", false, "Override local walk speed.");
        SpeedMult = config.Bind("Player", "SpeedMult", 1f, "Speed multiplier (base 2.5).");
        InvertControls = config.Bind("Player", "InvertControls", false, "Invert movement (negative speed).");
        Invisible = config.Bind("Player", "Invisible", false, "Invisibility: fake off-map network position (others can't see you; no interaction).");
        FakeScan = config.Bind("Player", "FakeScan", false, "Fake medbay scan animation (looks like you're scanning).");
        FakeCams = config.Bind("Player", "FakeCams", false, "Make security cameras show as in-use.");
        AutoTasks = config.Bind("Player", "AutoTasks", false, "Finish own tasks one by one in the background.");
        AutoTasksDelay = config.Bind("Player", "AutoTasksDelay", 1.5f, "Seconds between auto-completed tasks (never below 0.8).");
        AutoTasksDelay.Value = Mathf.Clamp(AutoTasksDelay.Value, 0.8f, 6f);
        SabAutoFix = config.Bind("Player", "SabAutoFix", false, "Repair any active sabotage the instant it starts (crew side).");
        ConsoleReach = config.Bind("Player", "ConsoleReach", false, "Use tasks and panels from far away.");
        ConsoleDist = config.Bind("Player", "ConsoleDist", 4f, "Console reach distance.");
        ConsoleDist.Value = Mathf.Clamp(ConsoleDist.Value, 1f, 15f);
        SkipDecon = config.Bind("Player", "SkipDecon", false, "Skip decontamination wait on MIRA and Polus.");
        AirshipSpawn = config.Bind("Player", "AirshipSpawn", false, "Airship: pick the spawn instead of the random screen.");
        AirshipSpawnId = config.Bind("Player", "AirshipSpawnId", 0, "Airship spawn index.");
        BuffNoCd = config.Bind("Buffs", "NoCooldowns", false, "Zero cooldown on every ability button.");
        BuffVentAny = config.Bind("Buffs", "VentAny", false, "Use vents with any role.");
        BuffVentWalk = config.Bind("Buffs", "VentWalk", false, "Move while sitting in a vent.");
        VentNetwork = config.Bind("Buffs", "VentNetwork", false, "Vent network: hop between any vents, even unconnected ones.");
        BuffKillReach = config.Bind("Buffs", "KillReach", false, "Override kill distance.");
        BuffKillDist = config.Bind("Buffs", "KillDistance", 2.5f, "Kill distance when the override is on.");
        BuffKillAny = config.Bind("Buffs", "KillAnyone", false, "Target anyone with the kill button, teammates included.");
        BuffKillAura = config.Bind("Buffs", "KillAura", false, "Kill everyone who walks into range.");
        AutoVentKill = config.Bind("Buffs", "AutoVentKill", false, "Impostor: dive into the nearest vent right after a kill.");
        BodyToVent = config.Bind("Buffs", "BodyToVent", false, "Host: on your kill, drop the body onto the nearest vent.");
        BuffNoKillCd = config.Bind("Buffs", "NoKillCooldown", false, "Zero kill cooldown. Host only.");
        BuffVanishKill = config.Bind("Buffs", "KillWhileVanished", false, "Phantom can kill while invisible. Host only.");
        BuffPhVanish = config.Bind("Buffs", "PhantomEndlessVanish", false, "Phantom: invisibility never runs out.");
        BuffVentSab = config.Bind("Buffs", "SabotageFromVent", false, "Impostor: sabotage button stays usable inside a vent.");
        BuffSsForever = config.Bind("Buffs", "EndlessShapeshift", false, "Shapeshift never runs out.");
        BuffSsQuiet = config.Bind("Buffs", "QuietShapeshift", false, "Shapeshift without the animation.");
        BuffAutoReport = config.Bind("Buffs", "AutoReportBodies", false, "Report every fresh body. Host only.");
        BuffEngVent = config.Bind("Buffs", "EngineerVentTime", false, "Engineer never runs out of vent time.");
        BuffEngCd = config.Bind("Buffs", "EngineerNoCooldown", false, "Engineer vent ability without cooldown.");
        BuffSciBat = config.Bind("Buffs", "ScientistBattery", false, "Scientist battery never drains.");
        BuffSciCd = config.Bind("Buffs", "ScientistNoCooldown", false, "Scientist vitals without cooldown.");
        BuffDetReach = config.Bind("Buffs", "DetectiveReach", false, "Detective can interrogate at any distance.");
        BuffImpTasks = config.Bind("Buffs", "ImpostorTasks", false, "Let impostors use task consoles.");
        BuffMapCd = config.Bind("Buffs", "NoMapCooldowns", false, "No cooldown on ladders and ziplines.");
        ChatSpamDelay = config.Bind("Player", "ChatSpamDelay", 2.5f, "Delay between spam chat sends (seconds).");
        DoorKeepOpen = config.Bind("Host", "DoorKeepOpen", false, "Keep all doors open, no minigame.");
        SabAutoLights = config.Bind("Host", "SabAutoLights", false, "Keep lights sabotaged.");
        SabSpamReactor = config.Bind("Host", "SabSpamReactor", false, "Repeat the main sabotage.");
        MultiSabotage = config.Bind("Buffs", "MultiSabotage", false, "Impostor: stack multiple sabotages at once (non-host).");
        VoteImmune = config.Bind("Host", "VoteImmune", false, "Host: you can't be voted out.");
        NoReports = config.Bind("Host", "NoReports", false, "Host: block all reports and meetings.");
        SabInfMushroom = config.Bind("Host", "SabInfMushroom", false, "Keep mushroom mixup active on Fungle.");
        MouseTeleport = config.Bind("Player", "MouseTeleport", false, "Teleport the local player with right-click.");
        MouseSelect = config.Bind("Player", "MouseSelect", false, "Select a player with the mouse (LMB) + wheel resize.");
        SelfDrag = config.Bind("Player", "SelfDrag", false, "Drag the local player by holding left-click on your avatar.");
        SelfDragSmooth = config.Bind("Player", "SelfDragSmooth", false, "Self-drag: glide smoothly instead of snapping.");
        SelfDragSpeed = config.Bind("Player", "SelfDragSpeed", 6f, "Self-drag glide speed (units/sec).");
        GhostAfterStart = config.Bind("Player", "GhostAfterStart", false, "Become a ghost locally after the match starts.");
        GameMaster = config.Bind("AutoHost", "GameMaster", false, "Game master: become a ghost after start (same as ghost-after-start).");
        FakeMapId = config.Bind("Lobby", "FakeMapId", 5, "Map for the lobby fake-map (0-5).");
        FakeMapId.Value = Mathf.Clamp(FakeMapId.Value, 0, 5);

        NameColor = config.Bind("Player", "NameColor", false, "Colored name (local only, your own player).");
        NameColorStyle = config.Bind("Player", "NameColorStyle", 4, "Colored-name preset index.");
        NameColorStyle.Value = Mathf.Clamp(NameColorStyle.Value, 0, 15);
        NameColorAnimated = config.Bind("Player", "NameColorAnimated", false, "Animate the colored name.");
        ChatLog = config.Bind("Chat", "ChatLog", false, "Write chat to Nocturne/ChatLog.txt.");
        ColorCmd = config.Bind("Chat", "ColorCmd", false, "Enable /c and /color chat color commands (host applies to sender, non-host to self).");
        ColorCmdNotify = config.Bind("Chat", "ColorCmdNotify", true, "Toast who used a color command.");
        ChatCmds = config.Bind("Chat", "ChatCmds", false, "Enable your chat commands: /kick /ban /color /role /mute /start /end /meeting /close /help.");
        BanWords = config.Bind("Chat", "BanWords", false, "Censor banned words (Nocturne/BanWords.txt).");

        LobbyPresets = config.Bind("Lobby", "Presets", "", "Saved lobby/role presets (serialized).");

        LobbyCloneMode = config.Bind("Lobby", "LobbyCloneMode", false, "Clone mode: LMB spawns at cursor, RMB removes, drag with mouse.");
        LobbyCloneShadow = config.Bind("Lobby", "LobbyCloneShadow", false, "Shadow clone trailing behind the player.");
        LobbyCloneGuard = config.Bind("Lobby", "LobbyCloneGuard", true, "Clones orbit around the player.");
        LobbyCloneGuardRadius = config.Bind("Lobby", "LobbyCloneGuardRadius", 2.5f, "Guard circle radius in world units.");
        LobbyCloneGuardRadius.Value = Mathf.Clamp(LobbyCloneGuardRadius.Value, 1f, 8f);
        LobbyCloneDrift = config.Bind("Lobby", "LobbyCloneDrift", false, "Clones wander around.");
        LobbyCloneMax = config.Bind("Lobby", "LobbyCloneMax", 50, "Max number of clones.");
        LobbyCloneMax.Value = Mathf.Clamp(LobbyCloneMax.Value, 1, 2000);
        LobbyCloneSpawnCount = config.Bind("Lobby", "LobbyCloneSpawnCount", 1, "Clones spawned per left-click (1-20).");
        LobbyCloneSpawnCount.Value = Mathf.Clamp(LobbyCloneSpawnCount.Value, 1, 20);
        NetCloneCount = config.Bind("Lobby", "NetCloneCount", 6, "Networked self-clones in a formation (1-2000).");
        NetCloneCount.Value = Mathf.Clamp(NetCloneCount.Value, 1, 2000);
        NetCloneMode = config.Bind("Lobby", "NetCloneMode", false, "LMB spawn / RMB remove networked self-clones at cursor.");
        LobbyCloneColorId = config.Bind("Lobby", "LobbyCloneColorId", -1, "Clone color override (-1 = source, 0-17 = color index).");
        LobbyCloneColorId.Value = Mathf.Clamp(LobbyCloneColorId.Value, -1, 17);
        LobbyCloneScale = config.Bind("Lobby", "LobbyCloneScale", 1f, "Clone scale.");
        CloneFormation = config.Bind("Lobby", "CloneFormation", 4, "Clone formation (0-18).");
        CloneFormation.Value = Mathf.Clamp(CloneFormation.Value, 0, 18);
        CloneFormationScale = config.Bind("Lobby", "CloneFormationScale", 1f, "Formation size multiplier.");
        CloneFormationScale.Value = Mathf.Clamp(CloneFormationScale.Value, 0.3f, 3f);
        CloneNaked = config.Bind("Lobby", "CloneNaked", false, "Bare clones (no cosmetics); the self-portrait tints them by region.");
        CloneFormationAnim = config.Bind("Lobby", "CloneFormationAnim", true, "Animate built formations.");
        CloneFormationAnimSpeed = config.Bind("Lobby", "CloneFormationAnimSpeed", 1f, "Formation animation speed.");
        CloneFormationAnimSpeed.Value = Mathf.Clamp(CloneFormationAnimSpeed.Value, 0.2f, 3f);
        LobbyCloneFormationCopies = config.Bind("Lobby", "LobbyCloneFormationCopies", 1, "Concentric copies when building a formation (1-5).");
        LobbyCloneFormationCopies.Value = Mathf.Clamp(LobbyCloneFormationCopies.Value, 1, 5);

        BetterChat = config.Bind("Chat", "BetterChat", true, "Better chat: richer input, copy/paste, bubble animation.");
        ChatWindow = config.Bind("Chat", "ChatWindow", false, "Draggable read+send chat window (works with the menu closed).");
        ChatHistorySize = config.Bind("Chat", "ChatHistorySize", 20, "How many messages to keep visible.");
        ChatHistorySize.Value = Mathf.Clamp(ChatHistorySize.Value, 5, 100);

        DarkChatTheme = config.Bind("Chat", "DarkChatTheme", true, "Dark chat theme matching the mod colors.");
        ChatBubbleSenderInfo = config.Bind("Chat", "ChatBubbleSenderInfo", true, "Level/platform next to the name in chat bubbles.");
        ChatTimestamps = config.Bind("Chat", "ChatTimestamps", false, "Show the exact send time under each chat bubble.");
        UnlimitedChatLength = config.Bind("Advanced", "UnlimitedChatLength", false, "Unsafe: remove the local message length limit.");
        SkipChatCooldown = config.Bind("Advanced", "SkipChatCooldown", false, "Unsafe: remove the delay between messages.");
        GhostChat = config.Bind("Chat", "GhostChat", false, "See dead chat while still alive.");

        AutoHostEnabled = config.Bind("AutoHost", "Enabled", false, "Host: auto-start matches in the lobby.");
        AutoHostMinPlayers = config.Bind("AutoHost", "MinPlayers", 4, "Minimum players before the start countdown.");
        AutoHostStartDelaySeconds = config.Bind("AutoHost", "StartDelaySeconds", 15, "Delay after reaching the minimum players.");
        AutoHostBackoffSeconds = config.Bind("AutoHost", "BackoffSeconds", 8, "Pause after a failed start attempt.");
        AutoHostInstantStart = config.Bind("AutoHost", "InstantStart", true, "Instant start instead of the vanilla countdown.");
        AutoHostWarmupSeconds = config.Bind("AutoHost", "WarmupSeconds", 5, "Warm-up after opening the lobby before countdowns.");
        AutoHostLoadGraceSeconds = config.Bind("AutoHost", "LoadGraceSeconds", 20, "Wait for players to load (0 = forever).");
        AutoHostFastStartPlayers = config.Bind("AutoHost", "FastStartPlayers", 13, "Player count for the short delay (0 = off).");
        AutoHostFastStartDelaySeconds = config.Bind("AutoHost", "FastStartDelaySeconds", 5, "Delay for the fast start.");
        AutoHostForceAfterMinutes = config.Bind("AutoHost", "ForceAfterMinutes", 0, "Start after N lobby minutes even below the minimum (0 = off).");
        AutoHostForceMinPlayers = config.Bind("AutoHost", "ForceMinPlayers", 2, "Minimum for forced starts.");
        AutoHostCancelBelowMin = config.Bind("AutoHost", "CancelBelowMin", true, "Cancel the countdown if players drop below the minimum.");
        AutoHostWaitLoadedPlayers = config.Bind("AutoHost", "WaitLoadedPlayers", true, "Wait for players to fully load in the lobby.");
        AutoHostReturnAfterMatch = config.Bind("AutoHost", "ReturnAfterMatch", true, "Return to the lobby from post-match screens.");
        AutoHostForceLastMinute = config.Bind("AutoHost", "ForceLastMinute", true, "Start in the lobby's last minute (if >=2 players).");
        AutoHostNotifications = config.Bind("AutoHost", "Notifications", true, "Show auto-host status.");

        DummyEnabled = config.Bind("Host", "DummySpawner", false, "Spawn dummy crewmates (host, in lobby).");
        DummyKey = config.Bind("Host", "DummySpawnKey", KeyCode.B, "Key to spawn a dummy.");
        DummyDoTasks = config.Bind("Host", "DummiesDoTasks", true, "Dummies walk around and fake tasks.");
        DummyFixSabotage = config.Bind("Host", "DummiesFixSabotage", true, "Dummies run to fix active sabotages.");
        DummyReportBodies = config.Bind("Host", "DummiesReportBodies", true, "Dummies report bodies, chat and vote.");

        MusicAccent = config.Bind("Music", "Accent", "Red", "Player accent theme.");
        MusicEqPreset = config.Bind("Music", "EqPreset", 16, "Equalizer preset index.");
        MusicEqPreset.Value = Mathf.Clamp(MusicEqPreset.Value, 0, 30);
        MusicPrevKey = config.Bind("Music", "PrevKey", KeyCode.LeftBracket, "Previous track.");
        MusicNextKey = config.Bind("Music", "NextKey", KeyCode.RightBracket, "Next track.");
        MusicPlayPauseKey = config.Bind("Music", "PlayPauseKey", KeyCode.None, "Play/pause.");
        MusicStopKey = config.Bind("Music", "StopKey", KeyCode.None, "Stop.");
        MusicVolumeUpKey = config.Bind("Music", "VolumeUpKey", KeyCode.None, "Volume up.");
        MusicVolumeDownKey = config.Bind("Music", "VolumeDownKey", KeyCode.None, "Volume down.");
        MusicToggleKey = config.Bind("Music", "ToggleKey", KeyCode.M, "Open/close the player.");

        LobbySnow = config.Bind("Lobby", "LobbySnow", false, "Legacy snow switch, migrated into LobbyWeather.");
        LobbyWeather = config.Bind("Lobby", "LobbyWeather", 0, "Lobby weather: 0 off, 1 snow, 2 rain, 3 leaves, 4 confetti. Local only.");
        LobbyWeather.Value = Mathf.Clamp(LobbyWeather.Value, 0, 4);
        if (LobbySnow.Value && LobbyWeather.Value == 0) LobbyWeather.Value = 1;
        LobbySnowAmount = config.Bind("Lobby", "LobbySnowAmount", 70, "Weather particles on screen (10-400).");
        LobbySnowAmount.Value = Mathf.Clamp(LobbySnowAmount.Value, 10, 400);
        BugRoomCycle = config.Bind("BugRooms", "Cycle", false, "Loop start/end in the current room and rejoin it.");
        BugRoomHunt = config.Bind("BugRooms", "Hunt", false, "Create a new room each cycle instead of rejoining the same one.");
        BugRoomTargets = config.Bind("BugRooms", "Targets", "BAWG", "Wanted code endings, 4 chars each, comma separated. Empty = judge by level instead.");
        BugRoomLog = config.Bind("BugRooms", "LogFound", true, "Save the room code when the level reads 1.");
        BugRoomDelay = config.Bind("BugRooms", "Delay", 2f, "Pause between cycles, seconds.");
        BugRoomDelay.Value = Mathf.Clamp(BugRoomDelay.Value, 1f, 10f);

        LobbyTheme = config.Bind("Lobby", "LobbyTheme", true, "Dark lobby shell theme.");
        MainMenuArt = config.Bind("Lobby", "MainMenuArt", true, "Own picture as the main menu background.");
        LobbyAnims = config.Bind("Lobby", "LobbyAnims", true, "Animations: right panel slide and Start button.");

        NoWinConditions = config.Bind("Lobby", "NoWinConditions", false, "Disable win-condition checks (the game won't end by itself).");
        HideAndSeekTwoSeekers = config.Bind("Lobby", "HideAndSeekTwoSeekers", false, "Host: custom seeker count in Hide and Seek.");
        SeekerCount = config.Bind("Lobby", "SeekerCount", 2, "Host: number of seekers in Hide and Seek.");
        SeekerInstantStart = config.Bind("Lobby", "SeekerInstantStart", false, "Hide and Seek: skip the crewmate head start, seeker is released at once.");
        FourImpostors = config.Bind("Lobby", "FourImpostors", false, "Host: 4 impostors in normal mode (needs >=9 players).");
        LooseHostOptions = config.Bind("Lobby", "LooseHostOptions", false, "Unlock host option limits (values beyond vanilla).");
        ForceMinValues = config.Bind("Lobby", "ForceMinValues", false, "Host option step 0.1 (when limits are unlocked).");
        CopyCodeOnDisconnect = config.Bind("Lobby", "CopyCodeOnDisconnect", true, "Copy the lobby code to the clipboard on disconnect.");

        Language = config.Bind("Interface", "Language", "en", "Menu language: ru, en.");
        ThemeIndex = config.Bind("Interface", "ThemeIndex", 11, "Accent theme index (11 = moonlight sky default).");

        BodyMode = config.Bind("Lobby", "BodyMode", "Disabled", "Client-side body style: Disabled, Horse, Seeker, Long, LongHorse.");
        MuteLobbyMusic = config.Bind("Lobby", "MuteLobbyMusic", true, "Mute only the lobby music locally.");
        SpoofPlatformEnabled = config.Bind("Spoof", "SpoofPlatformEnabled", false, "Spoof your platform in PlatformSpecificData.");
        SpoofPlatformIndex = config.Bind("Spoof", "SpoofPlatformIndex", 5, "0=Epic,1=Steam,2=Mac,3=Microsoft,4=Itch,5=iOS,6=Android,7=Switch,8=Xbox,9=PS,10=Starlight,11=Unknown");
        SpoofPlatformIndex.Value = Mathf.Clamp(SpoofPlatformIndex.Value, 0, 11);
        SpoofLevelEnabled = config.Bind("Spoof", "SpoofLevelEnabled", false, "Override the displayed level.");
        SpoofDeviceId = config.Bind("Spoof", "SpoofDeviceId", false, "Return a random, session-stable device id to the game.");
        SpoofLevelValue = config.Bind("Spoof", "SpoofLevelValue", 666, "Level to display (1-9999).");
        SpoofFriendCodeEnabled = config.Bind("Spoof", "SpoofFriendCode", false, "Custom friend code.");
        SpoofFriendCodeValue = config.Bind("Spoof", "SpoofFriendCodeValue", "", "Friend code value.");

        EventNotify = config.Bind("Events", "EventNotify", false, "Show notifications for game events.");
        EventConsole = config.Bind("Events", "EventConsole", false, "Persistent scrollable event log window.");
        EventNotifyChat = config.Bind("Events", "EventNotifyChat", false, "Also add event notifications to local chat.");
        EventFilterMask = config.Bind("Events", "EventFilterMask", 127, "Event log category filter bitmask.");
        ReplayView = config.Bind("Events", "ReplayView", false, "Match review window: player paths and event markers on a map.");
        ReplayFilterMask = config.Bind("Events", "ReplayFilterMask", 255, "Match review filter bitmask (event types + paths).");
        ReplayKey = config.Bind("Keys", "ReplayKey", KeyCode.None, "Toggle the match review window.");
        ReplayClearAfterMeeting = config.Bind("Events", "ReplayClearAfterMeeting", false, "Match review: clear all data (paths + events) after each meeting.");
        NotifyVotekick = config.Bind("Events", "NotifyVotekick", true, "Notify on votekick votes.");
        NotifySabotage = config.Bind("Events", "NotifySabotage", true, "Notify on sabotage.");
        SecurityNotify = config.Bind("Events", "SecurityNotify", true, "Toast when protection blocks something (fake meeting, spawn flood).");
        NotifyKill = config.Bind("Events", "NotifyKill", true, "Notify on kills.");
        NotifyMeeting = config.Bind("Events", "NotifyMeeting", true, "Notify on meetings/reports.");
        NotifyEject = config.Bind("Events", "NotifyEject", true, "Notify on ejections.");
        SpoofLevelValue.Value = Mathf.Clamp(SpoofLevelValue.Value, 1, 9999);
    }
}
